### ISSUE TITLE
.deb installer need deprecated gksu

### ISSUE THREAD

**Issue by nyxee** [deragon/autopoweroff#10]
I downloaded the .deb installer and used `dpkg -i ...` and i got a broken installed `autopoweroff` after it requested for gksu yet gksu is deprecated in Ubuntu 18.04.

**Comment by deragon** [comment]
Mmm....  From the 3.1.0 changelog, I see:

> Version 3.1.0 - 2019-04-31
> --------------------------------------------------
> 
> * [GH001](https://github.com/deragon/autopoweroff/issues/1):  Polkit replaces gksu.  This is the main feature of 3.1.0, allowing
>           Autopoweroff to work under modern Linux distributions such as
>           Ubuntu 18.04 LTS.  Thanks to @edgimar from GitHub for providing
>           the solution.

What version you downloaded and where did you get it?

**Comment by deragon** [comment]
Closing issue since this was already fixed in version 3.1.0 released on 2019-04-31.
