### ISSUE TITLE
Autopoweroff cancelfile filename mismatch.

### ISSUE THREAD

**Issue by mgutt** [deragon/autopoweroff#12]
At the moment [autopoweroff is not able to monitor my chrome remote desktop](https://github.com/deragon/autopoweroff/issues/11) session. Because of that I open the autopoweroff GUI directly after I'm connected and choose "disabled". If I confirm it, it returns "Autopoweroff is now disabled":
![2020-07-26 13_18_16](https://user-images.githubusercontent.com/10757176/88477706-8a1a6c00-cf42-11ea-9a40-703e53f47ed3.png)

But after some minutes the VM still shutdown. So I tried to set "disabled" AND switched to the configuration tab and choosed "yes" to restart autopoweroff.
![2020-07-26 13_19_26](https://user-images.githubusercontent.com/10757176/88477757-ea111280-cf42-11ea-89f0-7e33f3b521bb.png)

Now the VM stays active. Shouldn't the GUI ask for restart on the "Status & Command" tab, too?

**Comment by deragon** [comment]
Found the bug!  The GUI generates the file `/var/run/autopoweroff/autopoweroff-gui.cancel`, but the daemon looks for `/var/run/autopoweroff/autopoweroff.cancel` (not the same file).  I will fix this shortly.

**Comment by deragon** [comment]
I do not have the time to package `Autopoweroff` new version with this fix.  However, you can get the new code by performing a `git clone` on the master branch.  Packaging will require more time, unfortunately.

**Comment by deragon** [comment]
Fixed with Autopoweroff 4.0.0.

**Comment by deragon** [comment]
Fixed with Autopoweroff 4.0.0.
