### ISSUE TITLE
can't install in ubuntu 20.04 - missing python-gi

### ISSUE THREAD

**Issue by edwkmho** [deragon/autopoweroff#17]
System : Ubuntu 20.04.
Python installed : 3.8.5

root@ednote-p65:/home/edward/Downloads# dpkg -i autopoweroff-3.2.1-1.noarch.deb
dpkg: error: dpkg frontend lock is locked by another process
root@ednote-p65:/home/edward/Downloads# dpkg -i autopoweroff-3.2.1-1.noarch.deb
(Reading database ... 239996 files and directories currently installed.)
Preparing to unpack autopoweroff-3.2.1-1.noarch.deb ...
Unpacking autopoweroff (3.2.1-1) over (3.2.1-1) ...
dpkg: dependency problems prevent configuration of autopoweroff:
 autopoweroff depends on python-gi; however:
  Package python-gi is not installed.

dpkg: error processing package autopoweroff (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (245.4-4ubuntu3.3) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 autopoweroff
root@ednote-p65:/home/edward/Downloads# dpkg -i python-gi
dpkg: error: cannot access archive 'python-gi': No such file or directory
root@ednote-p65:/home/edward/Downloads# dpkg -i python3-gi
dpkg: error: cannot access archive 'python3-gi': No such file or directory

Python installed:
root@ednote-p65:/home/edward/Downloads# python --version
Python 3.8.5

**Comment by Jue-Xu** [comment]
Try `sudo apt-get install python-gi`

**Comment by deragon** [comment]
Try:  `apt install autopoweroff-3.2.1-1.noarch.deb`.  IIRC, it should download all the dependencies.  Let me know if that works.

**Comment by deragon** [comment]
No rep

**Comment by theluke** [comment]
Hi, I have the same issue, any idea?

**Comment by deragon** [comment]
@theluke, you tried [autopoweroff-daemon_4.2.0_all-ubuntu-20.04.deb](https://github.com/deragon/autopoweroff/releases/download/4.2.0/autopoweroff-daemon_4.2.0_all-ubuntu-20.04.deb)?
