### ISSUE TITLE
Autopoweroff crashes and prevents reboot

### ISSUE THREAD

**Issue by joesgarage** [deragon/autopoweroff#18]
Fresh install of ubuntu-20.04.2.0-desktop-amd64. 
Installed autopoweroff. Set parameters and minimize. 
After a few minutes, Pop up windows indicates program has crashed and should it send a report. 
Also, hangs on shutdown waiting for python 3.
Uninstalled autopoweroff, and above issues go away,

**Comment by deragon** [comment]
I need more detailed information to help you out.  Please provide a screenshot of the pop window.   "Waiting for Python 3".... I do not get how a program must wait for Python 3...  that is totally new.  Again, I need to see the full message.

Please send me the output of:

    fgrep -i autopoweroff /var/log/syslog*

Did you install by tarball or deb?

**Comment by deragon** [comment]
Please provide more feedback or else I will have to close this issue.  I really want to help you, but we need to exchange.

**Comment by joesgarage** [comment]
My apologies. I've been traveling for work and I haven't had the time to get back to that system at home. Perhaps close it for now.
-------- Original message --------From: Hans Deragon ***@***.***> Date: 3/11/21  10:44 AM  (GMT-05:00) To: deragon/autopoweroff ***@***.***> Cc: joesgarage ***@***.***>, Author ***@***.***> Subject: Re: [deragon/autopoweroff] Autopoweroff crashes and prevents reboot (#18) 
Please provide more feedback or else I will have to close this issue.  I really want to help you, but we need to exchange.

**Comment by deragon** [comment]
Ok.  If ever you get to reproduce it, with the latest version 4.0.0, please reopen.  I will be happy to help you out.
