### ISSUE TITLE
Requires Gnome 3.0

### ISSUE THREAD

**Issue by dineshmm23** [deragon/autopoweroff#2]
Sorry, but this application requires Gnome 3.0 resources that are not installed on this machine. Following is the specific error
`No module named gi
`

**Comment by deragon** [comment]
You mean that a dependency was missing?  How did you install Autopoweroff?  With .deb or .rpm?

**Comment by dineshmm23** [comment]
with .deb

**Comment by deragon** [comment]
`python-gi` is missing as a dependency.  I will add it for the next release.  In the meantime, install it separately using the command:

    sudo apt install python-gi

**Comment by deragon** [comment]
@dineshmm23, did you managed to pull Gtk?  What distribution are you using?  I found out on Fedora that pulling the 'gi' module for Python is not enough and Gtk must be added as a dependency.  I would like to know what distribution you are using.

**Comment by deragon** [comment]
This issue is fix in [release 3.1.0](https://github.com/deragon/autopoweroff/releases/tag/3.1.0).
