### ISSUE TITLE
Installing .deb fails

### ISSUE THREAD

**Issue by joesgarage** [deragon/autopoweroff#20]
When installing from the download folder, the popup box displays:
"Unable to install autopweroff-gui:
The following packages have unmet dependencies: "      but it doesn't list what the are.

Ubuntu 20.04.2 LTS

**Comment by deragon** [comment]
You need to install `autopoweroff` first, the server.  The GUI depends on the server.  Let me know if that worked for you.

Sorry for the late response.

**Comment by joesgarage** [comment]
I cannot get this to install.  I dont have a lot of experience with Linux,  see my try below:
I still get an error
joe:~/Downloads$ sudo dpkg -i autopoweroff*.deb 
Selecting previously unselected package autopoweroff-gui.
(Reading database ... 189737 files and directories currently installed.)
Preparing to unpack autopoweroff-gui_4.0.0_all.deb ...
Unpacking autopoweroff-gui (4.0.0) ...
dpkg: dependency problems prevent configuration of autopoweroff-gui:
 autopoweroff-gui depends on autopoweroff; however:
  Package autopoweroff is not installed.

dpkg: error processing package autopoweroff-gui (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 autopoweroff-gui

**Comment by deragon** [comment]
Do it in two steps:

`dpkg -i  autopoweroff_4.0.0_all.deb`

Then:

`autopoweroff-gui_4.0.0_all.deb`

I think what is happening is that dpkg attempts to install the gui before the server, thus it fails.  It is not smart enough to realize that the next package is the server and it should start with it first.  :(

**Comment by joesgarage** [comment]
SO,,  should the second command line look like:
sudo dpkg -i autopoweroff_4.0.0_all.deb   ??
or 
sudo autopoweroff_4.0.0_all.deb

again, I'm sorry, I'm not experienced in linux, just trying t use this program.  Thank you for being patient with me,.

**Comment by deragon** [comment]
Sorry for the long delays; very busy these days.

Try:  `sudo apt install ./*.deb`

I noticed that in the documentation, it suggest dpkg.   If you confirm that the command above works, I will fix the documenation.

**Comment by deragon** [comment]
Documentation fixed with commit https://github.com/deragon/autopoweroff/commit/0c55afe5707bf94d65d8f6e54e88bda18bbf805a.  Since I have not received any feedback from @joesgarage, I am making the assumption that this issue has been resolved.
