### ISSUE TITLE
Not working in Ubuntu 20.04

### ISSUE THREAD

**Issue by Ajtak** [deragon/autopoweroff#21]
![image](https://user-images.githubusercontent.com/4963819/122185326-4d729e80-ce8d-11eb-9440-26133284f66e.png)

**Comment by deragon** [comment]
Unfortunately, the most important information is not expanded in the screenshot.  In need to see _Traceback_.  Could you please resend?  And send also your configuration file if it does not contains sensitive data.

Nowhere in my code I make use of a function named sub().  Thus, the error is occurring in a module Autopoweroff makes use of.  _Traceback_ will show me the last line written for Autopoweroff where the error occured.

**Comment by deragon** [comment]
@Ajtak, you have to ask you to provide the _traceback_.  If I do not get it in the next few days, I will close this bug report as I cannot to anything further.
