### ISSUE TITLE
Can't install it on Ubuntu 20.04

### ISSUE THREAD

**Issue by pacid** [deragon/autopoweroff#28]
acid@lenovo:~/Downloads/autopoweroff-4.1.0$ sudo make install
[sudo] password for acid: 
make[1]: Entering directory '/home/acid/Downloads/autopoweroff-4.1.0'
 /usr/bin/mkdir -p '/usr/local/bin'
 /usr/bin/install -c usr/bin/autopoweroff-gui '/usr/local/bin'
 /usr/bin/mkdir -p '/usr/local/sbin'
 /usr/bin/install -c sbin/autopoweroff-gui sbin/autopoweroffd sbin/autopoweroff-uninstall sbin/autopoweroff-upgrade '/usr/local/sbin'
 /usr/bin/mkdir -p '/usr/local/etc/init.d'
 /usr/bin/install -c etc/init.d/autopoweroff.lsb etc/init.d/autopoweroff.rc-status etc/init.d/autopoweroff.redhat '/usr/local/etc/init.d'
 /usr/bin/mkdir -p '/usr/local/share/applications'
 /usr/bin/install -c -m 644 usr/share/applications/autopoweroff.desktop '/usr/local/share/applications'
 /usr/bin/mkdir -p '/usr/local/share/doc/autopoweroff'
 /usr/bin/install -c -m 644 AUTHORS COPYING doc/CHANGELOG.md INSTALL NEWS README.md '/usr/local/share/doc/autopoweroff'
 /usr/bin/mkdir -p '/usr/local/etc/autopoweroff'
 /usr/bin/install -c -m 644 etc/autopoweroff/autopoweroff.conf etc/autopoweroff/autopoweroff-metadata etc/autopoweroff/autopoweroff-logging.conf etc/autopoweroff/autopoweroff-logging-debug.conf '/usr/local/etc/autopoweroff'
 /usr/bin/mkdir -p '/usr/local/share/glade'
 /usr/bin/install -c -m 644 glade/autopoweroff.glade glade/autopoweroff.gladep glade/autopoweroff.trans '/usr/local/share/glade'
 /usr/bin/mkdir -p '/usr/local/etc/pam.d'
 /usr/bin/install -c -m 644 etc/pam.d/autopoweroff '/usr/local/etc/pam.d'
 /usr/bin/mkdir -p '/usr/local/share/pixmaps'
 /usr/bin/install -c -m 644 pixmaps/autopoweroff.png pixmaps/autopoweroff.svg '/usr/local/share/pixmaps'
 /usr/bin/mkdir -p '/usr/local/share/polkit-1/actions'
 /usr/bin/install -c -m 644 usr/share/polkit-1/actions/com.github.deragon.autopoweroff.policy '/usr/local/share/polkit-1/actions'
 /usr/bin/mkdir -p '/usr/local/share/autopoweroff/python/modules'
 /usr/bin/install -c -m 644 python/modules/ApoConfig-20220227T171836.py python/modules/ApoConfig.py python/modules/ApoDocumentation.py python/modules/ApoLibrary.py python/modules/ApoObserverDevice.py python/modules/ApoObserverHostsAlive.py python/modules/ApoObserverNoActionTimeRange-20220227T170038.py python/modules/ApoObserverNoActionTimeRange.py python/modules/ApoObserver.py python/modules/ApoObserverResources.py '/usr/local/share/autopoweroff/python/modules'
make  install-data-hook
make[2]: Entering directory '/home/acid/Downloads/autopoweroff-4.1.0'
echo "install-data-hook called."
install-data-hook called.
postinstall
/bin/bash: postinstall: command not found
make[2]: *** [Makefile:1063: install-data-hook] Error 127
make[2]: Leaving directory '/home/acid/Downloads/autopoweroff-4.1.0'
make[1]: *** [Makefile:945: install-data-am] Error 2
make[1]: Leaving directory '/home/acid/Downloads/autopoweroff-4.1.0'
make: *** [Makefile:897: install-am] Error 2

**Comment by deragon** [comment]
Fixed with https://github.com/deragon/autopoweroff/commit/ed8854c54e9ccf9c8daaca9ddb11f557635099d3.

However, I do not have the time to create a new release only for this fix.  As a workaround, just edit "Makefile", search for and replace `postinstall` with .`/postinstall` at the `install-data-hook` section like shown below.

```
install-data-hook:
	echo "install-data-hook called."
	./postinstall
```
