### ISSUE TITLE
Unable to use on Ubuntu 18.10

### ISSUE THREAD

**Issue by ithinkmatt** [deragon/autopoweroff#3]
Unable to use on Ubuntu 18.10 due to the removal of GKSU from Debian and Ubuntu in 18.04+. GKSU is deprecated. http://www.nongnu.org/gksu/

Can your app be used with PolicyKit instead?

**Comment by deragon** [comment]
Duplicate #1 .

**Comment by ithinkmatt** [comment]
@deragon I appreciate you taking time to respond. Thanks!
