### ISSUE TITLE
Feature request: CPU load as autopoweroff condition 

### ISSUE THREAD

**Issue by dreamflasher** [deragon/autopoweroff#4]
Use case: Automatically turning off an AWS machine, after process is finished.

**Comment by deragon** [comment]
This is an excellent request...  Now that my personal life gives me more time, I will (hopefully) work on this in the next few months.  I still need to refactor Autopoweroff before...  the code shows its age and adding dependencies needs to be more modular.

Thank you for suggestion and I am very sorry that so much time will have passed between your suggestion and a working stable solution.  I wish it could be different.

**Comment by deragon** [comment]
Implemented in Autopoweroff 4.0.0.
