### ISSUE TITLE
schedule daily start & stop

### ISSUE THREAD

**Issue by aghand0ur** [deragon/autopoweroff#40]
Hello @deragon
 
is it possible to use your tool to schedule daily start & stop hours for my workstation to save power?

**Comment by aghand0ur** [comment]
I was able to do that using bios wakeup on alarm settings..
I am not sure if the autopoweroff app is useful for this simple task too

**Comment by deragon** [comment]
Hi.  Yep, that is the way to do it.  It is already documented at:

https://github.com/deragon/autopoweroff#uefi--bios-configuration

There is also a way running a script that puts to sleep the computer.  I have to find time to document this though.  But you are good with your BIOS wakeup.
