### ISSUE TITLE
unistall

### ISSUE THREAD

**Issue by aghand0ur** [deragon/autopoweroff#41]
I installed the paper using
sudo apt install ./autopoweroff*****.deb

I am trying to uninstall it
can u please show me how to do that?
thanks

**Comment by aghand0ur** [comment]
```
which autopoweroffd
/usr/sbin/autopoweroffd

```

**Comment by deragon** [comment]
Yes, you need to learn more on how `apt` works.  It is the universal command line command on deb based distributions.
