### ISSUE TITLE
python-gi dependency not met and not installable for autopoweroff-gui

### ISSUE THREAD

**Issue by teasz** [deragon/autopoweroff#44]
Version: Linux Mint 21.1 Vera
Python Version: Python 3.10.6

autopoweroff daemon is installed with no problems
Used `apt install` and `sudo apt-get`, both says not installable or error

**user**:~$ apt install '/home/band/Downloads/autopoweroff-gui_4.2.0_all-ubuntu-20.04.deb'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'autopoweroff-gui' instead of '/home/band/Downloads/autopoweroff-gui_4.2.0_all-ubuntu-20.04.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 autopoweroff-gui : Depends: python-gi but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by deragon** [comment]
Greetings.  I bet you are trying to install autopoweroff-gui_4.2.0_all-ubuntu-**_20.04_**.deb on Ubuntu 22.04...

You should instead install autopoweroff-gui_4.2.0_all-ubuntu-**_22.04_**.deb.

But please, tell me on what OS you are attempting to install it.
