### ISSUE TITLE
Systems with a KVM switch

### ISSUE THREAD

**Issue by rac8006** [deragon/autopoweroff#5]
Autopoweroff has problem with loss of keyboard when switched to a different system.  Once it detects the loss of the keyboard it finishes the ApoObserverDevice threads.  Not what should be done with this condition.  The problem is that when you return the keyboard to the system it will shutdown even while you are typing.  
Maybe the autopoweroff should close the file and go into a sleep/wait looking for the keyboard.
When the keyboard is returned open the file again.  Not sure if the system should be tun=rned off if the keyboard is missing for the idletime.

**Comment by deragon** [comment]
I started working on this problem.  Hopefully it will be fixed in the next few weeks.  No promises though.

**Comment by rac8006** [comment]
It is fixed in the code I tried to upload.

Sent from Mail for Windows 10

**Comment by deragon** [comment]
Yes!   I remember our exchanges now.  Well, I modified the code to make use of pyinotify to dynamically change the list of devices to track as they are added and removed.  The code is still local on my laptop, but I plan to upload it soon in the official repository.

**Comment by rac8006** [comment]
I was not aware of pyinotify.  Here is what I did.  It was a quick and dirty fix.  It has been working since August.
try:
        fd.read(1)
      except IOError as ioerror:
        if ioerror.errno == errno.ENODEV:
          sendmsg("Device " + self.sDevice + " absent (No such device error)", \
                  priority=syslog.LOG_NOTICE)
          fd.close()
          while not Path(self.sDevice).exists():
            time.sleep(60)
          fd = open(self.sDevice, 'rb')
          continue

Sent from Mail for Windows 10

**Comment by deragon** [comment]
Fixed wit
