### ISSUE TITLE
Autopoweroff High CPU usage when only condition remaining is a living remote server

### ISSUE THREAD

**Issue by wadzinsky1** [deragon/autopoweroff#8]
running 'top' in terminal shows Autopoweroff using 100% of cpu once wait conditions are met but dependent machines still running.  Only noticed the issue since computer was plugged into a Kill-a-Watt device
Running Ubuntu 18.04 LTS <- did fresh install, same issue
![Screenshot from 2019-06-03 18-38-19](https://user-images.githubusercontent.com/51252720/58841428-6e158600-862f-11e9-9b82-08f377470791.png)
![Screenshot from 2019-06-03 18-40-11](https://user-images.githubusercontent.com/51252720/58841429-6eae1c80-862f-11e9-8af6-867132877b66.png)

**Comment by deragon** [comment]
Bug reproduced.  Working on it.

**Comment by deragon** [comment]
Fixed with release [3.2.1](https://github.com/deragon/autopoweroff/releases/tag/3.2.1).

**Comment by wadzinsky1** [comment]
Thank you for the fix.
________________________________
