### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by ssharks** [deragon/autopoweroff#9]
The application works only under Python 2, not with Python 3. This is not documented and Python 2 is EOL 1-1-2020.

**Comment by deragon** [comment]
I am in the process to move it to Python 3...  I already started the work, but I am not finished yet.  Ugh... I need to find the time to do this...

**Comment by deragon** [comment]
Done.  Code migrated to Python 3 in release [3.2.0 ](https://github.com/deragon/autopoweroff/releases/tag/3.2.0).
